# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Auto-ID and auto-reference operators."""

from arolla import arolla
from arolla.derived_qtype import derived_qtype
from koladata import kd

M = arolla.M | derived_qtype.M
P = arolla.P

kd.optools.set_namespace_docstring('kd_ext.ids', __doc__)


@arolla.optools.as_lambda_operator('_kd_ext_ids_get_metadata_schema')
def _get_metadata_schema(pair):
  return M.core.get_nth(pair, 0)


@arolla.optools.as_lambda_operator('_kd_ext_ids_get_actual_schema')
def _get_actual_schema(pair):
  return M.core.get_nth(pair, 1)


@kd.optools.add_to_registry(via_cc_operator_package=True)
@kd.optools.as_lambda_operator(
    'kd_ext.ids.auto_id',
    qtype_constraints=[
        kd.optools.constraints.expect_data_slice(P.name),
    ],
)
def auto_id(name):
  """Returns a description of the auto_id attribute.

  This is used as a value in `auto_attributes` to mark an attribute
  as an AUTO_ID attribute with `name` as the AUTO_ID namespace.
  The auto-assigned values of AUTO_ID attribute are generated in the form of
  <name>_<id>, where <id> is an auto-incrementing positive integer (e.g. foo_1,
  foo_2, etc.).

  Args:
    name: The namespace for the AUTO_ID attribute.

  Returns:
    Tuple that can be used as description of an AUTO_ID attribute.
  """
  metadata_schema = kd.schema.named_schema(kd.strings.join('__AUTO_ID__', name))
  str_schema = kd.STRING
  return M.core.make_tuple(metadata_schema, str_schema)


@kd.optools.add_to_registry(via_cc_operator_package=True)
@kd.optools.as_lambda_operator(
    'kd_ext.ids.auto_reference',
    qtype_constraints=[
        kd.optools.constraints.expect_data_slice(P.namespace),
    ],
)
def auto_reference(namespace):
  """Returns a description of the auto_reference attribute.

  This is used as a value in `auto_attributes` to mark an attribute
  as an auto_reference attribute within the `namespace` namespace.

  Args:
    namespace: The namespace for the auto_reference.

  Returns:
    Tuple that can be used as description of an auto_reference attribute.
  """
  metadata_schema = kd.schema.named_schema(
      kd.strings.join('__AUTO_REFERENCE__', namespace)
  )
  str_schema = kd.STRING
  return M.core.make_tuple(metadata_schema, str_schema)


@kd.optools.add_to_registry(via_cc_operator_package=True)
@kd.optools.as_lambda_operator(
    'kd_ext.ids.auto_reference_list',
    qtype_constraints=[
        kd.optools.constraints.expect_tuple(
            P.auto_schema_tuple, kd.qtypes.DATA_SLICE, kd.qtypes.DATA_SLICE
        ),
    ],
)
def auto_reference_list(auto_schema_tuple):
  """Returns a tuple that can be used for an auto_reference list attributes."""
  metadata_schema = _get_metadata_schema(auto_schema_tuple)
  actual_schema = _get_actual_schema(auto_schema_tuple)
  return M.core.make_tuple(
      kd.schema.list_schema(metadata_schema),
      kd.schema.list_schema(actual_schema),
  )


@kd.optools.add_to_registry(via_cc_operator_package=True)
@kd.optools.as_lambda_operator(
    'kd_ext.ids.with_auto_attributes',
    qtype_constraints=[
        kd.optools.constraints.expect_data_slice(P.schema),
    ],
    deterministic=False,
)
def with_auto_attributes(schema, /, **auto_attrs):  # pylint: disable=unused-argument
  """Returns a DataSlice with a new DataBag containing updated attrs in `schema`.

  This function sets schema attributes for auto-assigned values, such as
  AUTO_ID and AUTO_REFERENCE. These attributes must be marked in the schema's
  metadata as auto-assigned, so that downstream processing can distinguish them
  from regular attributes. Because of this metadata requirement,
  `schema.with_attrs` or similar methods are not sufficient — this dedicated
  method must be used instead.

  Values for `auto_attrs` should be "descriptions" generated by
  `kd_ext.ids.auto_id(name)` or similar descriptor functions. Each
  description encodes both the actual schema type (e.g. kd.STRING) and the
  metadata schema (e.g. a named schema for the auto-id namespace).

  Example:
    schema = kd_ext.ids.auto_attributes(
        kd.schema.new_schema(x=kd.INT32),
        foo_id=kd_ext.ids.auto_id('foo'),
        bar_id=kd_ext.ids.auto_id('bar'),
    )
    -> kd.schema.new_schema(
        x=kd.INT32,
        foo_id=kd.STRING,
        bar_id=kd.STRING,
        __schema_metadata__={
            'foo_id': kd.named_schema('__AUTO_ID__foo'),
            'bar_id': kd.named_schema('__AUTO_ID__bar'),
        },
    )

  Args:
    schema: The schema to add auto attributes to.
    **auto_attrs: Mapping from attribute name to auto-attribute descriptions,
      generated by `kd_ext.ids.auto_id(name)` or similar. Each
      description is a tuple encoding both the metadata schema and the actual
      attribute schema.

  Returns:
    A schema with the auto attributes added to both schema and metadata.
  """
  auto_attrs = arolla.optools.fix_trace_kwargs(auto_attrs)
  tuple_auto_attrs = M.derived_qtype.upcast(
      M.qtype.qtype_of(auto_attrs), auto_attrs
  )

  metadata_tuple = M.core.map_tuple(_get_metadata_schema, tuple_auto_attrs)
  actual_tuple = M.core.map_tuple(_get_actual_schema, tuple_auto_attrs)

  attr_names = M.qtype.get_field_names(M.qtype.qtype_of(auto_attrs))
  metadata_schemas = M.core.apply_varargs(
      M.namedtuple.make, attr_names, metadata_tuple
  )
  actual_schemas = M.core.apply_varargs(
      M.namedtuple.make, attr_names, actual_tuple
  )

  schema = arolla.abc.bind_op(
      'kd.core.with_metadata', schema, attrs=metadata_schemas
  )
  return arolla.abc.bind_op('kd.core.with_attrs', schema, attrs=actual_schemas)


@kd.optools.add_to_registry(via_cc_operator_package=True)
@kd.optools.as_backend_operator(
    'kd_ext.ids.auto_id_update',
    qtype_constraints=[
        kd.optools.constraints.expect_data_slice(P.x),
    ],
    qtype_inference_expr=kd.qtypes.DATA_BAG,
)
def auto_id_update(x):  # pylint: disable=unused-argument
  """Assigns auto_id values to all auto_id attributes in x.

  For each auto_id attribute in the schema, assigns a string id of the form
  '<namespace>_<counter>', where counter is an integer incremented for each
  item (starting from 1). The order of assignment is not guaranteed but will be
  the same on repeated calls to this operator with the same inputs.

  Example:
    schema = kd.schema.new_schema(a=kd.INT32)
    schema = kd_ext.ids.auto_attributes(
        schema,
        foo_id=kd_ext.ids.auto_id('foo'),
    )
    x = kd.new(a=kd.slice([1, 3, 2]), schema=schema)
    x.enriched(kd_ext.ids.auto_id_update(x))
      -> kd.new(
          a=kd.slice([1, 3, 2]),
          foo_id=kd.slice(['foo_1', 'foo_2', 'foo_3']),
      )

  Args:
    x: DataSlice with a schema that has auto_id attributes.

  Returns:
    A DataBag with auto_id attributes set.
  """
  raise NotImplementedError('implemented in the backend')
