# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Callable
from arolla import arolla
from koladata.types import data_bag
from koladata.types import data_slice


class DataItem(data_slice.DataSlice):
    def __call__(self, *args: Any, return_type_as: Any = ..., **kwargs: Any) -> data_slice.DataSlice | arolla.Expr: ...
    def bind(self, *args: Any, return_type_as: Any = ..., **kwargs: Any) -> DataItem: ...

    def __float__(self) -> float: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...

    # Methods inherited from DataSlice that return DataItem.
    # We aim to make this list exhaustive, but it's a best effort approach.

    @classmethod
    def from_vals(cls, x: Any, /, schema: data_slice.DataSlice | None = None) -> DataItem: ...

    def with_bag(self, bag: data_bag.DataBag | None, /) -> DataItem: ...
    def no_bag(self) -> DataItem: ...
    def fork_bag(self) -> DataItem: ...
    def freeze_bag(self) -> DataItem: ...
    def with_merged_bag(self) -> DataItem: ...
    def enriched(self, *bag: data_bag.DataBag) -> DataItem: ...
    def updated(self, *bag: data_bag.DataBag) -> DataItem: ...

    def with_schema(self, schema: data_slice.DataSlice, /) -> DataItem: ...
    def set_schema(self, schema: data_slice.DataSlice, /) -> DataItem: ...
    def with_schema_from_obj(self) -> DataItem: ...
    def embed_schema(self) -> DataItem: ...

    def with_attr(
        self,
        attr_name: str | data_slice.DataSlice,
        value: Any,
        overwrite_schema: bool | data_slice.DataSlice = False,
    ) -> DataItem: ...
    def with_attrs(
        self, *, overwrite_schema: bool | data_slice.DataSlice = False, **attrs: Any
    ) -> DataItem: ...
    def strict_with_attrs(self, **attrs: Any) -> DataItem: ...

    def clone(
        self, *, itemid: data_slice.DataSlice | None = None, schema: data_slice.DataSlice = None, **overrides: Any
    ) -> DataItem: ...
    def shallow_clone(
        self, *, itemid: data_slice.DataSlice | None = None, schema: data_slice.DataSlice = None, **overrides: Any
    ) -> DataItem: ...
    def deep_clone(self, schema: data_slice.DataSlice = None, **overrides: Any) -> DataItem: ...
    def deep_uuid(
        self, schema: data_slice.DataSlice = None, *, seed: str | data_slice.DataSlice = ''
    ) -> DataItem: ...
    def ref(self) -> DataItem: ...
    def stub(self, attrs: data_slice.DataSlice = []) -> DataItem: ...

    def list_size(self) -> DataItem: ...
    def dict_size(self) -> DataItem: ...
    def with_dict_update(self, keys: Any, values: Any = None) -> DataItem: ...
    def with_list_append_update(self, append: Any) -> DataItem: ...

    def follow(self) -> DataItem: ...
    def extract(self, schema: data_slice.DataSlice = None) -> DataItem: ...
    def get_itemid(self) -> DataItem: ...
    def get_present_count(self) -> DataItem: ...
    def get_size(self) -> DataItem: ...
    def with_name(self, name: Any) -> DataItem: ...


def register_bind_method_implementation(
    fn: Callable[..., DataItem],
): ...
