# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from typing import Any, Callable, overload, Self
from arolla import arolla
from koladata.types import data_bag
from koladata.types import data_slice
from koladata.types import type_defs


class DataItem(data_slice.DataSlice):
    def __call__(self, *args: Any, return_type_as: Any = ..., **kwargs: Any) -> data_slice.DataSlice | arolla.Expr: ...
    def bind(self, *args: Any, return_type_as: Any = ..., **kwargs: Any) -> DataItem: ...

    def __float__(self) -> float: ...
    def __index__(self) -> int: ...
    def __int__(self) -> int: ...
    def __hash__(self) -> int: ...

    # Methods inherited from DataSlice that return DataItem for DataItem, but
    # don't return Self for all DataSlice sub-classes (e.g. ListItem, DictItem).
    # We aim to make this list exhaustive, but it's a best effort approach.
    def list_size(self) -> DataItem: ...
    def dict_size(self) -> DataItem: ...
    def get_size(self) -> DataItem: ...

    def get_itemid(self) -> DataItem: ...
    def get_present_count(self) -> DataItem: ...

    @overload
    def get_attr(self, attr_name: data_slice.DataSlice, /, default: Any = None) -> data_slice.DataSlice: ...
    @overload
    def get_attr(self, attr_name: str, /, default: Any = None) -> DataItem: ...
    @overload
    def has_attr(self, attr_name: str) -> DataItem: ...
    @overload
    def has_attr(self, attr_name: data_slice.DataSlice, /) -> data_slice.DataSlice: ...
    @overload
    def maybe(self, attr_name: str) -> DataItem: ...
    @overload
    def maybe(self, attr_name: data_slice.DataSlice, /) -> data_slice.DataSlice: ...
    @overload
    def with_attr(self, attr_name: str, value: Any, overwrite_schema: bool = False) -> Self: ...
    @overload
    def with_attr(self, attr_name: data_slice.DataSlice, value: Any, overwrite_schema: bool | data_slice.DataSlice = False) -> data_slice.DataSlice: ...

    @overload
    def __add__(self, other: DataItem | int | float | str) -> DataItem: ...
    @overload
    def __add__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __radd__(self, other: DataItem | int | float | str) -> DataItem: ...
    @overload
    def __radd__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __sub__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __sub__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rsub__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __rsub__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __mul__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __mul__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rmul__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __rmul__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __truediv__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __truediv__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rtruediv__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __rtruediv__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __floordiv__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __floordiv__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rfloordiv__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __rfloordiv__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __mod__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __mod__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rmod__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __rmod__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __pow__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __pow__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rpow__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __rpow__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __and__(self, other: DataItem | bool | str | int | float) -> DataItem: ...
    @overload
    def __and__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rand__(self, other: DataItem | bool | str | int | float) -> DataItem: ...
    @overload
    def __rand__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __or__(self, other: DataItem | bool | str | int | float) -> DataItem: ...
    @overload
    def __or__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __ror__(self, other: DataItem | bool | str | int | float) -> DataItem: ...
    @overload
    def __ror__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __xor__(self, other: DataItem | bool | str) -> DataItem: ...
    @overload
    def __xor__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rxor__(self, other: DataItem | bool | str) -> DataItem: ...
    @overload
    def __rxor__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __eq__(self, other: DataItem | bool | str | int | float) -> DataItem: ...
    @overload
    def __eq__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __ne__(self, other: DataItem | bool | str | int | float) -> DataItem: ...
    @overload
    def __ne__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __gt__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __gt__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __ge__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __ge__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __lt__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __lt__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __le__(self, other: DataItem | int | float) -> DataItem: ...
    @overload
    def __le__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __lshift__(self, other: DataItem | int) -> DataItem: ...
    @overload
    def __lshift__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rshift__(self, other: DataItem | int) -> DataItem: ...
    @overload
    def __rshift__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __rlshift__(self, other: DataItem | int) -> DataItem: ...
    @overload
    def __rlshift__(self, other: data_slice.DataSlice) -> data_slice.DataSlice: ...
    @overload
    def __getitem__(self, key: DataItem | str | int | slice) -> DataItem: ...
    @overload
    def __getitem__(self, key: data_slice.DataSlice) -> data_slice.DataSlice: ...


def register_bind_method_implementation(
    fn: Callable[..., DataItem],
): ...
